export const notificationsData = [
  {
    id: 1,
    name: "Mark Webber",
    picture: `${process.env.PUBLIC_URL}/assets/images/avatar-mark-webber.webp`,
    operation: "reacted to your recent post",
    linked: "My first tournament today",
    read: false,
    date: "1m ago",
  },
  {
    id: 2,
    name: "Angela Gray",
    picture: `${process.env.PUBLIC_URL}/assets/images/avatar-angela-gray.webp`,
    operation: "followed you",
    linked: null,
    read: false,
    date: "5m ago",
  },
  {
    id: 3,
    name: "Jacob Thompson",
    picture: `${process.env.PUBLIC_URL}/assets/images/avatar-jacob-thompson.webp`,
    operation: "Has joined your group",
    linked: "Chess Club",
    read: false,
    date: "1 day ago",
  },
  {
    id: 4,
    name: "Rizky Hasanuddin",
    picture: `${process.env.PUBLIC_URL}/assets/images/avatar-rizky-hasanuddin.webp`,
    operation: "sent you a private message",
    linked: "My first tournament today",
    message:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    read: true,
    date: "5 days ago",
  },
  {
    id: 5,
    name: "Kimberly Smith",
    picture: `${process.env.PUBLIC_URL}/assets/images/avatar-kimberly-smith.webp`,
    operation: "commented on your picture",
    linked: `${process.env.PUBLIC_URL}/assets/images/image-chess.webp`,
    read: true,
    date: "1 week ago",
  },
  {
    id: 6,
    name: "Nathan Peterson",
    picture: `${process.env.PUBLIC_URL}/assets/images/avatar-nathan-peterson.webp`,
    operation: "reacted to your recent post",
    linked: "5 end-game strategies to increase your win rate",
    read: true,
    date: "2 weeks ago",
  },
  {
    id: 7,
    name: "Anna Kim",
    picture: `${process.env.PUBLIC_URL}/assets/images/avatar-anna-kim.webp`,
    operation: "left the group",
    linked: "Chess Club",
    read: true,
    date: "2 weeks ago",
  },
];
